# Generated by Django 4.1.5 on 2023-07-17 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='saldo',
        ),
        migrations.AddField(
            model_name='saldo',
            name='data_venda',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saldo',
            name='produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saldo',
            name='quantidade_vendida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
