# Generated by Django 4.1.5 on 2023-07-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_saldo_saldo_saldo_data_venda_saldo_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='saldo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=1000),
        ),
    ]
