# Generated by Django 4.1.5 on 2023-07-17 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_saldo_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saldo',
            old_name='saldo',
            new_name='faturamento',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='saldo',
            new_name='valor_venda',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='produto',
        ),
    ]
