# Generated by Django 4.1.5 on 2023-07-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_produto_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
