# Generated by Django 4.1.5 on 2023-07-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento', models.DecimalField(decimal_places=3, default=0, max_digits=1000)),
            ],
        ),
    ]
