# Generated by Django 4.1.5 on 2023-07-18 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldo',
            name='produto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
    ]
