# Generated by Django 4.2.3 on 2023-07-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_saldo_produto_alter_venda_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='produto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto'),
        ),
    ]
