# Generated by Django 4.2.3 on 2023-07-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_saldo_produto_alter_venda_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=3, default=0, max_digits=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Saldo',
        ),
    ]
