# Generated by Django 4.2.3 on 2023-07-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_faturamento_delete_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento', models.DecimalField(decimal_places=3, default=0, max_digits=1000)),
                ('produto', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Faturamento',
        ),
    ]
