# Generated by Django 4.2.3 on 2023-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_saldo_delete_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='faturamento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=1000),
        ),
    ]
