# Generated by Django 4.2.3 on 2023-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_produto_faturamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_vendas',
            field=models.IntegerField(default=0),
        ),
    ]
