# Generated by Django 4.2.3 on 2023-07-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_produto_qtd_vendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='qtd_vendas',
        ),
        migrations.AlterField(
            model_name='produto',
            name='faturamento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='faturamento',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_venda',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
