# Generated by Django 4.2.3 on 2023-07-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_produto_qtd_vendas_alter_saldo_faturamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='produto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
    ]
